### ISSUE TITLE
Redundant removal and reinsertion of node breaks focus on element

### ISSUE THREAD

**Issue by bisgardo** [elm/virtual-dom#178]
I have a table with a variable number of columns. The right-most column of the top row contains a button element which receives focus using an initial command when the app is first loaded. Immediately after, some data is loaded, causing one unrelated column C to be replaced by a few others.

The `td` nodes are rendered using `Html.Keyed.node` from `elm/html` and only the key of column C of the row changes.

The render flow doesn't remove just the unrelated column but also the one with the focused element. Even though the element is re-inserted it no longer has the focus that was intended.

Unless this is intended behavior I'll be happy to construct a minimal example project to demonstrate the behavior. If it is intended, I'll appreciate any ideas of a clean solution to my problem.

**Comment by peteygao** [comment]
@bisgardo This sounds like incorrect implementation on your end.

If you want to *not* recreate the existing rows (ergo losing focus) when new row(s) are added, you should be using `Html.Keyed.node` on the `tr` and *NOT* the `td` nodes.

**Comment by bisgardo** [comment]
@peteygao No rows are inserted or removed, just columns. And the problem is not that the `td`s are recreated: They get reused, but get (needlessly) detached from the tree for a brief moment. This is what causes the loss of focus.

**Comment by bisgardo** [comment]
Thanks @pravdomil for this excellent example.

I can recommend the following CSS snippet for debugging/illustration. It makes the DOM nodes flash when they're attached:

```css
* {
    animation-name: flash;
    animation-duration: .5s;
}
@keyframes flash {
    from {
        background-color: green;
    }
    to {
        background-color: inherit;
    }
}
```
